### ISSUE TITLE
Getting an error on Windows machines.

### ISSUE THREAD

**Issue by rliota** [rliota/JSCompile#2]
C:\workspace\local-server\services-ui\program-tracker\util>java -jar JSCompile.jar "..\web-app\ProgramTrackerWebApp\WebContent\js\tfa" TFAResources.js
Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at java.lang.String.split(Unknown Source)
        at rliota.util.JSParser.compile(JSParser.java:30)
        at rliota.util.JSParser.compile(JSParser.java:18)
        at rliota.util.JSCompile.main(JSCompile.java:12)

**Comment by rliota** [comment]
Fixed in v 2.1.1

**Comment by rliota** [comment]
Fixed in v 2.1.1
